### ISSUE TITLE
fatal error: json/json.h: No such file or directory

### ISSUE THREAD

**Issue by martiantomatoes** [Boteium/bashbullet2#5]
Tried to run make and got this error. Happens with the AUR package as well.
![Screenshot_2019-11-14_10-16-12](https://user-images.githubusercontent.com/6121225/68834843-cfa24c00-06c7-11ea-9322-4d938fa6459e.png)

**Comment by Boteium** [comment]
My bad. Jsoncpp shoud be listed as a dependency. It is generally available as jsoncpp or libjsoncpp-dev package on your Linux distribution.

**Comment by martiantomatoes** [comment]
Awesome. Works

**Comment by martiantomatoes** [comment]
Awesome. Works
